version: "3"

services:
  foundry:
    image: felddy/foundryvtt:release-10.290.0
    init: true
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - target: 30000
        published: 22300
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
    extra_hosts:
      - "foundryvtt.s3.amazonaws.com:52.92.209.74"

secrets:
  config_json:
    file: secrets.json

networks:
  default:
    name: main_network
    external: true