version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    - /var/www/html/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge
    - /etc/letsencrypt:/var/certs
    ports:
    - "80:80"
    - "443:443"

networks:
  default:
    name: main_network
    external: true