version: "3"

services:
  nginx:
    image: nginx:latest
    volumes:
    - ./conf.d:/etc/nginx/conf.d
    ports:
    - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']
networks:
  default:
    name: main_network