version: "3"

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    volumes:
    - ./conf.d:/etc/nginx/conf.d:ro
    - /var/www/html/.well-known/acme-challenge:/var/www/html/.well-known/acme-challenge
    - /etc/letsencrypt:/var/certs:ro
    - ./landing/index.html:/var/www/html/index.html:ro
    ports:
    - "80:80"
    - "443:443"

networks:
  default:
    name: main_network
    external: true

# For generating certs:
# sudo certbot certonly --webroot --webroot-path /var/www/html/ -d marconzet.pl
