version: '3'

services:
  terraria:
    image: ghcr.io/beardedio/terraria:vanilla-1.4.4.9
    ports:
      - '22777:22777'
    restart: unless-stopped
    environment:
      - world=test.wld
    volumes:
      - ./config:/config
    tty: true
    stdin_open: true